name: Update USOM Blocklist

on:
  schedule:
    - cron: '0 * * * *'
  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run the update script
        run: python update_list.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          git add USOM-AdGuard-DNS.txt
          
          if ! git diff --staged --quiet; then
            git commit -m "Update USOM list - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            git push
          else
            echo "No changes to commit."
          fi
